### ISSUE TITLE
Support multiple exported components in Single File

### ISSUE THREAD

**Issue by playerx** [amritk/gulp-angular2-embed-sass#3]
At this moment, transformation works only for first component

**Comment by amritk** [comment]
Hey @playerx could you give me an example? I'm not really using this myself until angular 2 is closer to being ready for production so I'm not quite sure what doesn't work.

**Comment by playerx** [comment]
Hi, here is an example:
_slide.ts_

``` ts
import {Component}  from 'angular2/core'


@Component({
    selector: 'slide',
    styleUrls: ['slide.ts.scss'],
    template: `
        <div class="slide" (click)="onClick()">
            <slidechild></slidechild>
        </div>
    `,
    directives: [UISlideChild]
})
export class UISlide {

}


@Component({
    selector: 'slidechild',
    styleUrls: ['slidechild.ts.scss'],
    template: `
        <div class="slidechild">
            Just Child Element
        </div>
    `
})
export class UISlideChild {

}
```

**slide.ts.scss** - is replaced correctly
**slidechild.ts.scss** - is not changed

**Comment by amritk** [comment]
Ah yes I see now. I will check it out. Thanks!

**Comment by amritk** [comment]
Just an update, I have been working on it. Nothing I have tried has worked yet, but I have an idea that might.

**Comment by amritk** [comment]
Sorry man I think its going to require a complete rewrite for this. I might give it another go when I switch back to angular 2.

**Comment by amritk** [comment]
Getting back into angular 2 now so I will restart work on this project. This issue however goes against the style guide: https://angular.io/docs/ts/latest/guide/upgrade.html#!#follow-the-angular-style-guide which states 

> The Rule of 1 states that there should be one component per file. This not only makes components easy to navigate and find, but will also allow us to migrate them between languages and frameworks one at a time. In this example application, each controller, component, service, and filter is in its own source file.

So I will be closing this issue.
